### ISSUE TITLE
FANPLOT: Plotting multiple radars with overlapping FOVs, missing vectors

### ISSUE THREAD

**Issue by SEC-VT** [SuperDARN/pydarn#100]
# BUG 

When plotting multiple radars with overlapping FOVs, vectors are missing in the resultant plot.

## Priority

- [x ] Major - misrepresentation of data, failure in a common situation 

## Example of the bug 

The following code, plotting a handful of northern hemisphere radars:
```python
site_file_dict = {'bks':'sddata/20160306.1200.02.bks.fitacf.bz2',
                  'fhe':'sddata/20160306.1200.02.fhe.fitacf.bz2',
                  'cly':'sddata/20160306.1200.02.cly.fitacf.bz2',
                  'fhw':'sddata/20160306.1200.02.fhw.fitacf.bz2',
                  'kap':'sddata/20160306.1200.03.kap.fitacf.bz2',
                  'wal':'sddata/20160306.1201.00.wal.fitacf.bz2',
                  'sto':'sddata/20160306.1201.00.sto.fitacf.bz2'}

fanplot = {}

for radar_site in site_file_dict.keys():
    sdfpath = site_file_dict[radar_site]
    with bz2.open(sdfpath) as grid_file:
        fstream = grid_file.read()
        SDarn_read = pydarnio.SDarnRead(fstream, True)
        records = SDarn_read.read_fitacf()
    kwargs = {'boundary':True, 'zmax':200, 'zmin':-200, 'groundscatter':True, 'lowlat':40, 'scan_index':89}
    # only plot the colorbar once
    if radar_site == 'bks':
        fanplot[radar_site] = pydarn.Fan.plot_fan(records, colorbar=True, **kwargs)
    else:
        fanplot[radar_site] = pydarn.Fan.plot_fan(records, colorbar=False, **kwargs)
```
produces the following plot:

![image](https://user-images.githubusercontent.com/33470230/108636349-a471e500-7452-11eb-9042-4149e5647f22.png)

Hiding the overlapping radars (STO and KAP in this case) will show the missing vectors at CLY:
```python
site_file_dict = {'bks':'sddata/20160306.1200.02.bks.fitacf.bz2',
                  'fhe':'sddata/20160306.1200.02.fhe.fitacf.bz2',
                  'cly':'sddata/20160306.1200.02.cly.fitacf.bz2',
                  'fhw':'sddata/20160306.1200.02.fhw.fitacf.bz2',
#                   'kap':'sddata/20160306.1200.03.kap.fitacf.bz2',
#                   'sto':'sddata/20160306.1201.00.sto.fitacf.bz2',
                  'wal':'sddata/20160306.1201.00.wal.fitacf.bz2'}

fanplot = {}

for radar_site in site_file_dict.keys():
    sdfpath = site_file_dict[radar_site]
    with bz2.open(sdfpath) as grid_file:
        fstream = grid_file.read()
        SDarn_read = pydarnio.SDarnRead(fstream, True)
        records = SDarn_read.read_fitacf()
    kwargs = {'boundary':True, 'zmax':200, 'zmin':-200, 'groundscatter':True, 'lowlat':40, 'scan_index':89}
    # only plot the colorbar once
    if radar_site == 'bks':
        fanplot[radar_site] = pydarn.Fan.plot_fan(records, colorbar=True, **kwargs)
    else:
        fanplot[radar_site] = pydarn.Fan.plot_fan(records, colorbar=False, **kwargs)
```
yields

![image](https://user-images.githubusercontent.com/33470230/108636360-b3f12e00-7452-11eb-92e8-0a9473afb2ad.png)

### Data Location

FITACFs from VT.

## Potential Bug Location 

Line 204 in pydarn/fan.py: Fan.plot_fan() method
![image](https://user-images.githubusercontent.com/33470230/108636005-96bb6000-7450-11eb-9f82-066d151f15c0.png)

## Potential Solution(s)

In above lines, set the alpha of the RGBA value to 0.

Doing so produces the following result:
![image](https://user-images.githubusercontent.com/33470230/108636307-6379d080-7452-11eb-9c4c-4e13906fa64a.png)

**Comment by mts299** [comment]
@SEC-VT created a PR working from within pyDARN. 

This will be a HOTFIX so it will be sent out as a PATCH release hopefully soon.

Thank you again for spotting this and being on the ball with fixing it!

**Comment by mts299** [comment]
Thank you again for fixing this it is now released in patch release!
