### ISSUE TITLE
FOV limited to 75 range gates by default

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#116]
# BUG 

FOV only shows the first 75 range gates which maybe not be correct for radars with a large FOV. 

## Priority

- [ ] Minor - typo, incorrect naming, fails on specific uncommon situation
- [x] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Example of the bug 

![Figure_1](https://user-images.githubusercontent.com/6520530/111198052-c7d90d00-8584-11eb-81c3-4a4beacbf72c.png)

### Data Location

`make_grid` with FHW data or any known radar with more than 75 Rage gates. 

## Potential Bug Location 

*Please note this is not required.*
*If you can link to some code in pyDARN where you think the bug is coming from this will help the developer fix it sooner.*

## Potential Solution(s)

https://github.com/SuperDARN/pydarn/blob/a61a5e37cd7a50e1c40629866fbe0564d1433222/pydarn/plotting/fan.py#L50

Change the default and get the range gate value from the hardware files.

**Comment by mts299** [comment]
@billetd @carleyjmartin @Devin-Huyghebaert @ecbland here is a purposed solution to this problem:
In the `SuperDARNRadars` class that has all the radar info, I add `45_range` and `15_range` on to the radars info that will hold the max range gate for both 45 and 15 km modes then we can use that number (45km) to generate the FOV plots when 75 gates are not quite good enough like for `plot_grid`? 

We can get the range gate values from RAWACF/FITACF files since Hardware files seem to be non-standardized right now.

**Comment by carleyjmartin** [comment]
Just so I'm understanding right: I want to plot a FOV plot, the FOV will be plotted using the number of range gates dictated by the data file I'm reading in. If I'm not reading in a data file, it grabs the number of range gates from `45_range` in `SuperDARNRadars`?
If so, that's good with me.

**Comment by mts299** [comment]
No data file is used for a FOV plot originally I was hoping the Hardware file would be used but `gates` is a bit ambiguous in meaning right now (DSWG issue)

Yes, it would grab from `45_range`. Another reason to not grab from the data file is that we don't have FOV for 15 km mode so we wouldn't be able to plot 225 range gates and end up in the same spot. For now, we can say `plot_fan` and `pllot_fov` assume 45km mode as it is the most common mode.

Thus FOV files are just dependent on us changing the SuperDARNRadars and we can direct users thee for that kind of info and then it is well established at least in one place :p
