### ISSUE TITLE
MAP file Plotting

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#119]
# New Feature

**Name**: `plot_map`

**module**:  `map.py`

**package**: `/plottting`

## Scope

- [x] plot map data
- [x] plot in MLT magnetic polar coordinates
- [x] option to change parameters to plot
- [x] fov coverage
- [ ] information KP voltage diff

## Description

This feature will focus on the vectors and the other parts of the plotting will come. 

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [ ] Is this a minor change i.e., new small utility function?
-  [x] Is this a major change i.e., new plotting function?
-  [ ] Do you need help developing it? 
-  [x] Have you created a pyDARN GitHub [project](https://github.com/SuperDARN/pydarn/projects) to show the tasks needed to be done? 

## User Interface 

`plot_map(map_data)`

**Comment by mts299** [comment]
**NEW** convection map plot PR is up and here is a list of tasks to get it completely done: 
- [x] plot `vector.vel.median` LOS velocity
- [x] plot `model.vel.median` modeled velocity 
- [x] calculate and plot fitted convection velocities 
- [x] plot power points
- [x] plot spectral width points
- [ ]  plot convection potential 
- [ ]  plot HMB 
- [ ]  add_imfdirection
- [ ]  add_mapinfo 
- [ ] Day-night terminator **Marina Schmidt**
- [ ] add to test suite - **Marina Schmidt**
- [ ] coordinate system

If you would like to do one of these unticked tasks let me know and I can assign it to you and you can make an Issue to get started on it :)

**Comment by carleyjmartin** [comment]
**Potential Contours and HMB**

I have created a new branch `ehn/convection_contours` where you can currently find a basic outline of calculating and plotting the potential contours and the Heppner-Maynard boundary which builds on the convection map branch - not merged with Dan's update yet. 
Anyway, I had a few TODO's and felt that it should be more of a discussion for all devs than me doing what I think.

Discussion points:
- [ ] Contour locator: At the moment I have a FixedLocator for ever 5 kV from -100 to 100 with a gap (-1,1) to ensure 0 is white/transparent, works for my needs but probably not good for pyDARN. 
- [ ] Assess colormap needs, using a generic matplotlib green-white-purple for now, probably will require custom one. RST uses the same color for + and -, do we want this too?
- [ ] Edge color of contour plotting, I'm using contourf to plot the contours, but there's a bug when you use alpha<1 where the edged of the contours do not take alpha, there's a whole big discussion about it on matplotlibs github, at the moment I don't know how to fix this and don't think we want to go with alpha=1.
- [ ] z-ordering for all components

To Do:
- [ ] Currently calling the HMB and contour plotting from the top plot_mapdata method - might not be correct, so feel free to amend in any way.
- [ ] No evaluation of 'Coords' done, this and the previous branch only consider plotting in magnetic/MLT.
- [ ] Merge Dan's fix for the fitted velocities into branch
- [ ] Some kwargs (like boundary) appear to break on this branch, I do not know why.
- [ ] Lon and lat shift in all areas of the code (fitted vels too)
- [ ] Gap at pole (I think I know how to fix that)
- [ ] Needs southern testing (I don't have any southern map files to hand)

Here's an example, it looks a bit of a mess but everything is on there:
```python
map_file = "/Users/carley/Documents/data/maps/20150310.n.map"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,record=180, parameter=pydarn.MapParams.FITTED_VELOCITY, lowlat=60)
plt.show()
```
![Screen Shot 2022-03-01 at 9 24 17 AM](https://user-images.githubusercontent.com/60905856/156196992-3f57bf99-7402-4b48-8aeb-7f378c3a0c25.png)

**Comment by billetd** [comment]
Regarding the contours, it may be very challenging to do variable colours as it would need it's own colour bar for the potentials. The solution by other plotting tools is for one solid colour on the contours (maybe a different one for positive and negative cells?), with actual potential values displayed on the levels. For example (this is done in IDL, which has an option to add the level labels in. Not sure if there's a similar, easy way to do it in python?):

![image](https://user-images.githubusercontent.com/26160732/156401517-25fd55df-da8e-4266-968c-c4a46eda39d7.png)

**Comment by carleyjmartin** [comment]
Do we want to redo this issue as a Convection Map Discussion Mega-Thread? I guess it was originally for the vectors only and I don't know if people would look for this title when I say go look at the convection map issue? Plus a newer issue will stick it in people's faces to see.

**Comment by mts299** [comment]
@carleyjmartin do you mind closing then opening yours contour plots?
