### ISSUE TITLE
Pip installable

### ISSUE THREAD

**Issue by kkotyk** [SuperDARN/pydarn#12]
Feature request: make pydarn pip installable from git link.

**Comment by mts299** [comment]
Will do after release 1.0 happens :) 

First PR reviews like the wind!

**Comment by asreimer** [comment]
This is already possible, isn't it? This works:

    pip install git+https://github.com/SuperDARN/pydarn.git

And you can select a particular branch or commit. See here: https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by mts299** [comment]
It does work with the git url, just updating install notes on it. 

Closing the issue as it is resolved.
