### ISSUE TITLE
Modulation of polar plotting functionalities

### ISSUE THREAD

**Issue by billetd** [SuperDARN/pydarn#128]
# New Feature

**Name**: *axis_polar*

**module**:  *polar.py, fan.py, scan.py, grid.py* 

**package**: *plotting/*

## Scope

- [ ] Modularise polar axis functionality which is used in `plot_fan`, `plot_fov', 'plot_grid`, and future things like `plot_map`. 
- [ ] Include the new functionality to plot in geographic and geomagnetic coordinates, not just magnetic local time.

*What will the feature do?*
- [ ] Return a polar plot axis object of the chosen coordinate system with appropriate labels and lower latitude boundary, based on user input, or defaults (depending on the input file, e.g., choosing an appropriate lower latitude boundary for mid-latitude radars).

*What will the feature not do?* 
- [ ] Return non-polar axis objects

## Description

Currently, if no axis object is passed into plotting functions like `plot_fan`, `plot_fov' and `plot_grid`, very similar code is used in each which generates a polar plot by default. This can be modularised and re-used by all those functions, as well as future ones which will use a polar plot such as `plot_map`.

Additionally, keyword options for `plot_fan`, `plot_fov' and `plot_grid`, which control the polar plot, are not consistent. The inclusion of a new function to generate a polar axis, `axis_polar`, will ensure each function which calls it will have access to same set of customisation keywords.

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [x] Is this a minor change i.e., new small utility function?
-  [ ] Is this a major change i.e., new plotting function?
-  [ ] Do you need help developing it? 
-  [ ] Have you created a pyDARN GitHub [project](https://github.com/SuperDARN/pydarn/projects) to show the tasks needed to be done?

**Comment by mts299** [comment]
@billetd did you accomplish this with you polar plot code or still need to add more?
