### ISSUE TITLE
Zenodo link in citations warnings

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#129]
# BUG 

Currently the warnings for citations give the zenodo link for v1.1.0, suggested changes below. 

## Priority

- [x] Minor - typo, incorrect naming, fails on specific uncommon situation
- [ ] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Potential Bug Location 

Found on lines 443 in rtp.py and 262 of acf.py.

## Potential Solution(s)

We could change it to : *https://zenodo.org/record/3727269* which will then link to whatever the latest version, or we should update it to *https://zenodo.org/record/4558130* which is the current version (or wait to update at 2.1), but then we would have to remember to update the user warnings before each release.

**Comment by mts299** [comment]
On it!
