### ISSUE TITLE
Switching default branch to develop

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#137]
# Discussion 

Moving default branch to `develop`

## Description

Wondering if we should move the GitHub default branch to `develop` this means we get the benefit of the PRs always merging to `develop` to avoid mistakes to `master` as I have done since merging to `master` only happens every few times. We also get the advantage of automatically closing issues when the linked PR is merged. The GitHub repo page will show `develop` rather than `master` might be the only issue but if people are using `pip3` for installing or zenodo and developers are only using the repo as recommended. 
 
## Category

- [ ] User-friendly  
- [x] Software Design
- [ ] Data related
- [x] Capabilities
- [ ] Clarity 
- [x] Workflow

**Comment by carleyjmartin** [comment]
I'd be happy for develop to be default branch, like you said, it stops any accidental merges with master, which I have done 🙄

**Comment by mts299** [comment]
Amen!!!

**Comment by mts299** [comment]
Switched!

**Comment by mts299** [comment]
Closing as no issues has been brought to my attention, if anyone does, they can make an issue.
