### ISSUE TITLE
Fan plots drop the rightmost beam

### ISSUE THREAD

**Issue by SEC-VT** [SuperDARN/pydarn#139]
# BUG 

In plotting/fan.py, the _plot_fan_ method does not plot the last beam in a scan.

## Priority

- [ ] Minor - typo, incorrect naming, fails on specific uncommon situation
- [x] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Example of the bug 

This is an example of the output from the plotting/fan.py/Fan._plot_fov_ method, overlaid with a scatter plot of the *thetas* and *rs* output. Note the extra beam clockwise of the FOV.
![image](https://user-images.githubusercontent.com/33470230/112887831-9fcbcc80-90a1-11eb-86c1-76f521abd070.png)
The same beam is dropped in the _plot_fan_ routine which actually plots the vectors.

### Attempts

I'm working on a PR that adds cartopy functionality to the fan plots which addresses this issue.

### Data Location

Using INV and BKS fitacfs from Virginia Tech.

## Potential Bug Location 

The issue stems from lines 299-314 (in _plot_fov_):
```python
        if boundary:
            # left boundary line
            plt.polar(thetas[0:ranges[1], 0], rs[0:ranges[1], 0],
                      color='black', linewidth=0.5)
            # top radar arc
            plt.polar(thetas[ranges[1] - 1, 0:thetas.shape[1] - 1],
                      rs[ranges[1] - 1, 0:thetas.shape[1] - 1],
                      color='black', linewidth=0.5)
            # right boundary line
            plt.polar(thetas[0:ranges[1], thetas.shape[1] - 2],
                      rs[0:ranges[1], thetas.shape[1] - 2],
                      color='black', linewidth=0.5)
            # bottom arc
            plt.polar(thetas[0, 0:thetas.shape[1] - 2],
                      rs[0, 0:thetas.shape[1] - 2], color='black',
                      linewidth=0.5)
```
The _right_ boundary line and _bottom_ arc are subtracting **2** from the shape, instead of **1**. The _top_ radar arc should not subtract anything.
Similarly, in line 183 (_plot_fan_ method):
```python
        # Begin plotting by iterating over ranges and beams
        for gates in range(ranges[0], ranges[1]-1):
            for beams in range(thetas.shape[1] - 2):
                # Index colour table correctly
                cmapindex = (scan[gates, beams] + abs(zmin)) /\
```
"thetas.shape[1] - **2**" should only subtract **1**.

## Potential Solution(s)

See above. Subtracting 1 instead of 2 should fix it.

## Extra Notes

*Please provide other pertinent details about this feature:*
- *Debian Buster*
- *Python version 3.7*
- *Examples of what the visual output should look like*
### Things to come:
![image](https://user-images.githubusercontent.com/33470230/112892926-f63c0980-90a7-11eb-9865-9f9cc999307a.png)

**Comment by billetd** [comment]
Hi @SEC-VT, thank you for pointing this out. 

When the code was first written, I was sure there was a reason why it was "-2" and not "-1", but for the life of my I can't figure out why now. I just tested the fix and seems like no problems arose, and it wasn't pulling random data from somewhere it shouldn't be.

I'll make a new PR now.

**Comment by mts299** [comment]
@SEC-VT Thank you again for helping with this, make sure to work from the `develop` branch. 

Also, I have a branch already made for just installing cartopy ish to pyDARN if you want to look at it. Also, can you make an issue New Featur about the cartopy work you are doing so others don't work on it at the same time.  

Thanks again!!

**Comment by SEC-VT** [comment]
@billetd Awesome! I hesitated raising this issue for a bit because it seemed intentional and I thought I was missing something. 😄 

@mts299 Will do! RE: scope of PRs in general, is there a preference for one big one or many smaller PRs (all related to fan plots)? There are few improvements to the fan plot routine I've got in the oven (cartopy, datetime input, performance optimizations, etc.) and I don't want to unintentionally bombard the group with notifications.

**Comment by carleyjmartin** [comment]
I wouldn't worry about notifications, we can turn off what we don't want to see! Little ones will get through review quicker too.

Also, there is already an issue for the datetime input for fan plots that I brought up #124 , so if you're working on it feel free to assign yourself to that as I haven't worked on it in this repo, but I did write the code already for our website to get a record number from datetime obj.
