### ISSUE TITLE
[EHN] Stick and Ball 

### ISSUE THREAD

**Issue by SEC-VT** [SuperDARN/pydarn#143]
# Enhancement

**Name**: `plot_fan`

**module**:  `fan.py`

**package**: `/plotting`

## Scope

*What will the feature do?*
- [x] replace repeated calls to plt.fill with fewer calls to plt.pcolormesh
- [x] implement datetime object input
- [x] add toggle for current magnetic polar plots / cartopy based plots
- [x] implement cartopy based geographic plots
- [x] add solar terminator to cartopy plots

*What will the feature not do?* 
- [ ] magnetic cartopy plots

## Description

The current method of plotting each range-gate in a scan loops through each beam and gate and issues a call to _plt.fill()_. For each radar, that's on the order of ~1500 calls to a function with modest overhead. This can be reduced to two calls with similar overhead by leveraging the plt.pcolormesh routine. While the cumulative overhead of the previous method isn't massive, it makes producing long animations of all the northern hemisphere radars out to be a lengthy process. (EX: 20 radars, 17.6 s/frame vs  0.6s/frame on AMD Ryzen 7 1800X)

In addition, cartopy plotting functionality has been added.
![image](https://user-images.githubusercontent.com/33470230/113062664-1809bf00-9182-11eb-94f6-b469cb8fa374.png)
The cartopy update will include a day/night terminator (#50 ) as provided in the cartopy library and datetime object handling (#124 ) for the _scan_index_ parameter. There's also a simple check to ensure that the datetime requested is actually in the dmap file being handled.

A PR (or several) will be coming in the next few days (or so 😄 ) to implement these updates.

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [ ] Is this a minor change i.e., new small utility function?
-  [x] Is this a major change i.e., new plotting function?
-  [ ] Do you need help developing it? 
-  [x] Have you created a pyDARN GitHub [project](https://github.com/SuperDARN/pydarn/projects) to show the tasks needed to be done? 

## User Interface 

`plot_fan(dmap_data, scan_index=dt.datetime(...), polar=False)`

## Extra Notes
- There are a lot of parameters that can alter cartopy plots. The default being shown here uses an orthographic projection at the pole rotated so noon is always on top, but it would probably be a good idea to pass the option to customize this up to the main _plot_fan_ routine.
- I'm not certain what style of terminator is provided by cartopy, so some improvements might be made there
- I'm also working on a different vector representation for the cartopy plots that makes multi-radar plots slightly more digestible.  This ends up requiring some fudging of the range-gate centers and marching geodesics that I'd want some more feedback on eventually. That's going to be a whole other issue.
**Ball and stick plots:**
![image](https://user-images.githubusercontent.com/33470230/113064125-6ae47600-9184-11eb-80c9-34121fd24194.png)

**Comment by mts299** [comment]
Thank you for all this! This looks amazing. 

@SEC-VT before you get too ahead of things, the day/night terminator we will probably use is one developed by a summer student who uses very accurate models and isn't dependent on cartopy. So you may want to remove that option for now. 

We don't want a large dependency on cartopy as it isn't always the easiest library to install and should be an option to be installed with pyDARN or outside install of the user's choice. So keep this in mind when developing that portion to allow freedom for users not to depend on cartopy.

**Comment by mts299** [comment]
This is done in various PRs and now we just need the ball and stick which has an issue open for
