### ISSUE TITLE
New Feature: Ball and Stick Plots

### ISSUE THREAD

**Issue by SEC-VT** [SuperDARN/pydarn#144]
# New Feature

**Name**: `ballandstick`

**module**:  `fan.py`

**package**: `/plotting`

## Scope

*What will the feature do?*

- [ ] Plot regular fan plots, but with balls and sticks pointing in the direction of the gate

## Description

![image](https://user-images.githubusercontent.com/33470230/113065290-95cfc980-9186-11eb-8999-7feff4648940.png)
Teased in #143, a plot that shows not just the range gate and color, but also has a stick indicating gate orientation. When plotting multiple radars, it can get tricky to discern which gates point where with overlapping FOVs.

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [ ] Is this a minor change i.e., new small utility function?
-  [x] Is this a major change i.e., new plotting function?
-  [ ] Do you need help developing it? 
-  [ ] Have you created a pyDARN GitHub [project](https://github.com/SuperDARN/pydarn/projects) to show the tasks needed to be done? 

## User Interface 

`plot_fan(dmap_data, stick_plot=True)`

### Problems
1. The current implementation shown fudges the gate centers by finding the center of a rectangle defined by the corners. This isn't exactly accurate.
2. The gate azimuths are found by marching a geodesic from center to center. This creates a problem at the "knee" in the FOV, where the next gate is shifted in altitude. Really, the best way to solve this problem and have more accurate azimuths is #141.
3. Scaling with matplotlib quiver plots can be tricky/buggy, especially when combined with cartopy. The most recent version of cartopy (0.18) encounters difficulty when wrapping features around the anti-prime meridian (180 W/E), but only with certain extents and projections.

**Comment by mts299** [comment]
I will be working on #141 right away so please leave that to me :p 

Again good job on all this!!
