### ISSUE TITLE
BUG/Question: R-T Plots Start time shifts to previous 15 min interval

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#167]
# BUG 

When plotting summary plots or range time plots using data read in that does not start at 15 minute intervals. The plot starts from the nearest previous 15 minute interval, and fills in with white spaces. I.e in the examples below I'm plotting data from 00:25 - 01:48 on 2nd March 2021 for Saskatoon beam 2. 

<img width="782" alt="Screen Shot 2021-05-21 at 9 49 07 AM" src="https://user-images.githubusercontent.com/60905856/119165040-4e451b80-ba1a-11eb-9479-a735df5dfe55.png">

## Priority

- [x] Minor - typo, incorrect naming, fails on specific uncommon situation
- [ ] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Example of the bug 

I've narrowed it down to these lines (412-421) in `rtp.py`

```python
# setup some standard axis information
        # Upon request of Daniel Billet and others, I am rounding
        # the time down so the plotting x-axis will show the origin
        # time label
        # TODO: may need to be its own function
        rounded_down_start_time = x[0] -\
            timedelta(minutes=x[0].minute % 15,
                      seconds=x[0].second,
                      microseconds=x[0].microsecond)
        ax.set_xlim([rounded_down_start_time, x[-1]])
```

### Attempts

As the end time works fine and ends with whatever time you give it, I tried to remove the `% 15` from line 418. This results in the plot skipping to the nearest previous hour instead of 15 mins, making even more white space. 
<img width="777" alt="Screen Shot 2021-05-21 at 9 49 55 AM" src="https://user-images.githubusercontent.com/60905856/119165331-9c5a1f00-ba1a-11eb-8177-d46888afbd7a.png">

So then replaced the `% 15` with `% 1` and this now works as I wanted it to.
<img width="765" alt="Screen Shot 2021-05-21 at 9 49 34 AM" src="https://user-images.githubusercontent.com/60905856/119165412-b09e1c00-ba1a-11eb-8ae1-2719f8149ffb.png">

## Potential Bug Location 

see above and in the timeseries plot function at lines 671-674!

## Potential Solution(s)

see above in attempts
```python
rounded_down_start_time = x[0] -\
            timedelta(minutes=x[0].minute % 1,
                      seconds=x[0].second,
                      microseconds=x[0].microsecond)
```

## Extra Notes

The notes next to this say: 
```python
# Upon request of Daniel Billet and others, I am rounding
 # the time down so the plotting x-axis will show the origin
 # time label
```
So if @billetd and others want to argue that this is a feature and not a bug, then go ahead. :P 
If this is intended usage, is there a way I can override this as a default rather than me amending the source code in my version of pydarn? Obviously, when plotting an entire day it's hardly noticeable, but it's a large chunk from an hour or two of data.

**Comment by carleyjmartin** [comment]
This was originally discussed in PR: #20  before my time.
It seemed as though everyone was happy with the solution which forces the x-axis to have a tick at the start of the x-axis, but fills in any time before the 'start time' as white space.

My only issue is that we would be representing the time before the start time as 'no data' when there actually is data to go there, but also this is a very very minor issue, so if everyone is happy as is, I'm happy to wait on any responses and close this issue in a week or two. 

I was developing this for use via our website, and was thinking that it would be easier to accept time in 15 min intervals rather than 1 min, so I can solve this on my end instead.

**Comment by mts299** [comment]
I think its something to look into, would you mind taking this on?

**Comment by carleyjmartin** [comment]
After discussing, these are the action points on this issue:
- [ ] Give a keyword option to/not to round off the start of the x-axis in time
- [ ] If the rounding off is done, fill in the time with the data and make sure the time period on the top of the plot if correct to the rounding.
- [ ] If option to round is chosen, make sure the start of the x-axis has a tick label (i.e. the rounding is the same as the tick frequency)
