### ISSUE TITLE
Fan.plot_fan() not working in pydarn v2.1

### ISSUE THREAD

**Issue by ninaer** [SuperDARN/pydarn#173]
# BUG 

After installing the new pydarn v2.1 Fan.plot_fan() gives me an UnboundLocalError.

## Priority

- [ ] Minor - typo, incorrect naming, fails on specific uncommon situation
- [ ] Major - misrepresentation of data, failure in a common situation 
- [X] Urgent - failure in usage, large misrepresentation

## Information
**python version**: Python 3.7.7

## Example of the bug 

``` 
station ='han'
wanted_time = dt.datetime(2014,12,18,9,30) 
date=dt.datetime.strftime(wanted_time.date(),"%Y%m%d")
file = f'data_path_location/{date}/fitacf3/{date}.{station}.fitacf' 

reader = pydarnio.SDarnRead(file)
fitacf_data = reader.read_fitacf()

fanplot = pydarn.Fan.plot_fan(fitacf_data, scan_index=2)
plt.show()
```

Output:
```

  File "path_location/TEST.py", line 35, in <module>
    fanplot = pydarn.Fan.plot_fan(fitacf_data, scan_index=2)

  File "/home/nina/anaconda3/envs/testenvi/lib/python3.7/site-packages/pydarn/plotting/fan.py", line 175, in plot_fan
    if not scan_time:

UnboundLocalError: local variable 'scan_time' referenced before assignment
```

### Attempts

It worked in the older v2.0.1 version, and then after installing the newest version it didn't work any longer. By reinstalling the older version the code works again. 

Time-Series plots, Rang-Time plots and Summary plots worked using the examples given on https://pydarn.readthedocs.io/en/master/user/fan/ for python v2.1, but not the Fan plots.

### Data Location

The data is stored locally on my computer as .fitacf files and are just directly read from the respective path.

## Potential Bug Location 

I have not tried other data from other stations, currently looking at data from Hankasalmi (han) on the 18 December 2014, and I think it might be an issue that comes from reading the data. I've written some scripts to retrieve optical data and I would get this error if I suddenly used data that was formatted in the standard method and I would have to change the code slightly so it could read the data properly. However, I'm not a programmer so this might not be the issue here. The fitacf-file does get read correctly using the summary-plots function in pydarn v2.1.

## Extra Notes

*Please provide other pertinent details about this feature:*
- *Examples of what the visual output should look like*
- *Other data files that show the same bug*
- *How to access data files to test out the bug*

**Comment by mts299** [comment]
Hi @ninaer thank you for pointing this out. I will fix the bug right away but due to the holidays coming up in Canada it may be slow getting it out into a release patch. 

You can use a `datetime` object to also locate the scan too if you need something working right away and want to use pyDARN 2.1

**Comment by ninaer** [comment]
Hi  @mts299, and thank you! I'm ok with using the older version for now so there is no need to hurry for my sake. I wasn't really sure what priority I should label the issue with but since it caused a part of the code to not function the urgent-box seemed reasonable.

**Comment by mts299** [comment]
@ninaer it is fixed! so if you want to test the PR that will help make the release faster :) is the pull request #174 

No no urgent is good! I am glad you could point it out and are testing the new version of pyDARN!

**Comment by ninaer** [comment]
@mts299 ok, I'll test the PR tomorrow!

**Comment by ninaer** [comment]
Hi again @mts299, I've been trying to test the pull request for this issue using the method as described on https://pydarn.readthedocs.io/en/master/dev/testing/, but this is my first time testing a PR and I'm having some issues. I'm not sure if it is because I don't really know how to do it (the instructions are good, but there is still some stuff that is not very obvious for a new person). I can see that I end up installing the correct branch in my testing-environment from the changes on the fan.py file, but using you test script in the PR gives me issues related to the installation of this pydarn-branch. First it gives me the hardware-files problem, so I copy the files from another working pydarn directory to the hdw-folder, but then when trying the test-script I get an "AttributeError: module 'pydarn' has no attribute 'SuperDARNRead'"-error.

It probably is an installation error of the branch, but I'm not sure how to fix it.
