### ISSUE TITLE
Adak Island East radar data out of order

### ISSUE THREAD

**Issue by Oriolebird** [SuperDARN/pydarn#175]
# BUG 

The hemisphere and range gate data for Adak Island East in the radars dictionary contained in the SuperDARNRadars class are swapped.

## Priority

- [X] Minor - typo, incorrect naming, fails on specific uncommon situation

## Information
**python version**:  3.8.10

## Potential Bug Location 

Line 361 in superdarn_radars.py.

## Potential Solution(s)

Swap locations of 75 and Hemisphere.North in text.

## Extra Notes

This error is visible in the FOV documentation as ADW is not plotted along with all other northern hemisphere radars, so the documentation may need to be updated as well.

**Comment by mts299** [comment]
Thank you for noticing this! I will address it right away.
