### ISSUE TITLE
from pydarn import dict2dmap not working

### ISSUE THREAD

**Issue by mardet987** [SuperDARN/pydarn#18]
currently have to use 

> from pydarn.utils.conversions import dict2dmap

in io/borealis.py

**Comment by mts299** [comment]
@mardet987 I think the potential issue here is that you put a Borealis folder inside the io folder so I am wondering if there is some level structuring going on making Borealis not see pyDARN's method in other folders. 

Would If be an option to move the Borealis files into io/utilities and remove the borealis folder? 

Generally, python libraries are supposed to be as flat as possible and I think this might be why with how `__init__.py` files work.

**Comment by mardet987** [comment]
Sorry, I think this is no longer an issue! I think it was something to do with the order of imports in the init file, and I was able to get this to work correctly at some point.
