### ISSUE TITLE
Small Typo in radar_pos.py

### ISSUE THREAD

**Issue by Oriolebird** [SuperDARN/pydarn#201]
# BUG 

In the radar_fov function, if coords are set to AACGM and no date is given in the arguments, date is set to the current time.
In the v2.2 branch (and current develop branch) this line reads "date = datetime.datetime.now()" when it should say "date = dt.datetime.now()" as datetime is imported as dt at the beginning of the file.

## Priority

- [X] Minor - typo, incorrect naming, fails on specific uncommon situation

## Potential Bug Location 

Typo is on line 97 of utils/radar_pos.py.

## Potential Solution(s)

datetime.datetime.now() should be changed to dt.datetime.now()

**Comment by carleyjmartin** [comment]
Hey @Oriolebird I've just tagged this issue in a suggestion in the new release so we can get the fix in asap. 
Can you just have a quick check that the suggestion I put in the comment is the same one as what you described above?

If you find any more typos feel free to use the suggestions tool too!
