### ISSUE TITLE
plot_fan() creates new axes instead of plotting on passed in axes

### ISSUE THREAD

**Issue by ellioday** [SuperDARN/pydarn#215]
# BUG 

Passing a custom axes into pydarn.Fan.plot_fan(..., ax=some_ax, ....), rather than plotting on some_ax, a new axis is made on top of some_ax instead

## Priority

- [x] Minor - typo, incorrect naming, fails on specific uncommon situation
- [ ] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Information
**python version**: 3.9
**OS**: Ubuntu 20.04.3 LTS
**matplotlib version**: 3.4.2

## Example of the bug 

```py
SDARN_read = pydarn.SuperDARNRead(path)
fitacf_data = SDARN_read.read_fitacf()

fig = plt.figure(figsize=[6, 6])
ax = fig.add_gridspec(4, 20)
ax1 = fig.add_subplot(ax[0:3,0:17], polar=True)
ax1.set_ylim(90, 40)
ax1.set_xticks([0, np.radians(45), np.radians(90), np.radians(135),
					np.radians(180), np.radians(225), np.radians(270),
					np.radians(315), np.radians(360)])
ax1.set_xticklabels(['00', '03', '06', '09', '12', '15', '18', '21', '00'])
ax1.set_theta_zero_location("S")
ax1.set_yticks(np.arange(40, 90, 10))
ax1.set_thetamin(290-50)
ax1.set_thetamax(290+50)

pydarn.Fan.plot_fan(fitacf_data, scan_index=1, ax=ax1, groundscatter=False, colorbar=False, title=False)
```

produces:

![image](https://user-images.githubusercontent.com/71040773/142873026-4b2cce49-b4de-428e-afab-cedc48bc4e09.png)

you can see the custom axes hidden behind the one created and plotted on by pydarn

### Attempts

See potential bug location/solution

### Data Location

BKS fitacf data from Virginia tech

## Potential Bug Location 

Line 190-191 in Fan.py

```py
        beam_corners_aacgm_lats, beam_corners_aacgm_lons, thetas, rs, ax = \
            cls.plot_fov(dmap_data[0]['stid'], date, **kwargs)
```
no ax is passed into ```cls.pot_fov()```, resulting in plot_fov creating the new ax in lines 368-374

```py
        # Setup plot
        # This may screw up references
        if ax is None:
            # Get the hemisphere to pass to plotting projection
            kwargs['hemisphere'] = SuperDARNRadars.radars[stid].hemisphere
            # Get a polar projection using any kwarg input
            ax = Projections.axis_polar(**kwargs)
```

## Potential Solution(s)

pass ax (and ranges that is also missing) into ```cls.plot_fov() ```

```py
        beam_corners_aacgm_lats, beam_corners_aacgm_lons, thetas, rs, ax = \
            cls.plot_fov(dmap_data[0]['stid'], date, ax=ax, ranges=ranges, 
						                     **kwargs)
```

now plots on passed ax
```py
pydarn.Fan.plot_fan(rad_data["bks"], scan_index=dtime, ax=ax1, groundscatter=False, colorbar=False, title=False)
```
![image](https://user-images.githubusercontent.com/71040773/142871981-8be432d7-01d7-4cd2-8cd8-50565d0b1fcf.png)

**Comment by mts299** [comment]
Hi @ellioday thank you for this! 

I will get the fix out right away! Would you be interested in testing the PR once it's ready for testing?

**Comment by mts299** [comment]
@ellioday the PR is made if you want to test and merge it :)

**Comment by ellioday** [comment]
thanks @mts299, I've tested and merged on my machine and it works fine now. I'm not too experienced with GitHub so I'm not sure if I'm to hit the close button or to leave it to the dev?

**Comment by mts299** [comment]
Hi, @ellioday no worries, it was merged by @carleyjmartin and it auto closes the issue :) 

We will be making a patch release soon, would you be interested in testing that PR too?

**Comment by ellioday** [comment]
Sure @mts299, I would be happy to test it. I presume that would just be running a few examples when the PR is made?

**Comment by mts299** [comment]
Hi @ellioday the pr is made #217 Please test it out :)
