### ISSUE TITLE
Updating Readthedocs

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#223]
# Documentation 

Its that time of the year again where we need to review the changes to readthedocs. 

Gonna do a once over to make sure things are up to date. Please let me know if you notice anything in the current documentation. 

## Purpose

- [x] update
- [ ] new 
- [ ] remove
- [ ] typo/grammar change
- [ ] markdown improvement

### List to update 

- [ ] seperate and update `radar_fov` from radar and hardware information
- [ ] update `fan` plots as they are missing `grid` and `labels`

**Comment by mts299** [comment]
Here is the current develop readthedocs: https://pydarn.readthedocs.io/en/develop/

**Comment by carleyjmartin** [comment]
Making a list of requests from users for next release and updates needed:
- Better documentation on summary plots - include all options and options from time series and range time here too so user doesn't have to go rooting around. 
- ACF plots updates for new options.
-

**Comment by carleyjmartin** [comment]
To streamline our documentation updating, I've combined all our current open issues on documentation into one big issue so we can keep on top of it. See #269 :)
