### ISSUE TITLE
Wish List?

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#240]
# Question

Something that might be interesting is having a user wishlist things people want to see in pyDARN or have available. 
I am wondering if we want to try and do this as we get more of the standard visuals in and how would we do this? 

One idea was a wishlist template for issues... we could try my only fear is an over abundent issues appearing :p 

Projects would be a good place to have it but of course not sure if non-pydarn github users can add to a project.

**Comment by J-LeeLC** [comment]
pydarn能画GPS/TEC 图吗

**Comment by mts299** [comment]
@J-LeeLC can you give an example of what you mean by GPS/TEC even a paper with a plot showing the data involving SuperDARN data?
