### ISSUE TITLE
Some issues with the scripts provided in documentation

### ISSUE THREAD

**Issue by KhanalKrishna** [SuperDARN/pydarn#267]
I ran the plotting scripts in the documentation to see if the accompanying figures are generated. I experienced the following problems.

I used,
pyDARN v3.0
macOS Catalina v10.15.7
matplotlib v3.5.1

**RTP plot**
import matplotlib.pyplot as plt
import pydarn
fitacf_file = "20150419.1801.00.rkn.fitacf"
sdarn_read = pydarn.SuperDARNRead(fitacf_file)
fitacf_data = sdarn_read.read_fitacf()

pydarn.RTP.plot_range_time(fitacf_data, beam_num=fitacf_data[0]['bmnum'], range_estimation=pydarn.RangeEstimation.RANGE_GATE)
plt.title("Radar {:d}, Beam {:d}".format(fitacf_data[0]['stid'], fitacf_data[0]['bmnum']))  

plt.show()

This produces the following error:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/89372135/177695542-66864926-c0c1-40aa-93f4-06c8960ab730.png">

**FOV plot**

import matplotlib.pyplot as plt
from datetime import datetime
import pydarn

pydarn.Fan.plot_fov(66, datetime(2015, 3, 8, 15, 0), radar_label=True)
plt.show()

This produces,
<img width="488" alt="image" src="https://user-images.githubusercontent.com/89372135/177693927-0862d0bb-fd83-4fcb-953c-446f7933fe6a.png">

which is not what it's supposed to be

**map plot**
import matplotlib.pyplot as plt 
import pydarn

map_file = "20190111.north.map2"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)

pydarn.Maps.plot_mapdata(map_data, record=150, 
                         parameter=pydarn.MapParams.FITTED_VELOCITY,
                         lowlat=60, colorbar_label='Velocity m/s',
                         contour_fill = True,
                         contour_fill_cmap= 'RdBu',
                         contour_colorbar = True,
                         contour_colorbar_label='Potential (kV)',
                         pot_minmax_color = 'r',
                         map_info=True, imf_dial=True, hmb=True)

plt.show()

This produces following error:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/89372135/177695855-9ac84d3a-17eb-4492-bb4b-e8163c4d5ff1.png">

**Comment by mts299** [comment]
@KhanalKrishna Looks like plot_fov is plotting the southern pole...

**Comment by KhanalKrishna** [comment]
@mts299 , it returns 3.0

**Comment by mts299** [comment]
@KhanalKrishna do the following
``` bash 
pip uninstall pydarn
pip3 install pydarn
```

**Comment by carleyjmartin** [comment]
See issue #269 for more docs stuff!
