### ISSUE TITLE
DOCS: Updates to Documentation Required Before Next Release!

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#269]
# Documentation 

Issue thread for all documentation changes required before the next release!
Please amend list below if you find anything new to update. 
Any discussion welcome in the comments, please tick anything off if you have updated it!

This includes issues previously brought up in #267 , #264 , #223 

## Details

Fans/Fov:
- [x] Include `grid` and `labels` options
- [x] Update docs for multi-fan and fov on one plot - this can be done but is not completely straight forward or the same for both coordinate systems or projections. (Read in ccrs for multi in geo and set coords and projs kw for each).

Maps:
- [x] 3rd example should read: `pydarn.Maps.plot_mapdata(map_data, record=150)`

Summary Plots:
- [x] Include all options and options from time series and range time here too so user doesn't have to go rooting around.

ACF:
- [x] ACF plots updates for new options.

Aux:
- [x] Explanation of differences between using coords, range_estimation and projs keywords in different plots.
- [x] New range estimate HALF_SLANT:  https://doi.org/10.1029/2022RS007429 
- [x] Proj and Coords GEO show view from below Earth. Proj Polar and Coords AACGM show view from *through* the Earth.
- [x] Subplot axes issues/solution, no support for custom read in of axes.

**Comment by bharatreddy** [comment]
@carleyjmartin: Hi Carley, I'm still not sure if the citation  (https://doi.org/10.1029/2022RS007429) is still directly relevant to HALF_SLANT. The paper focuses on the virtual height characteristics of the Christmas Valley radars. We might need to discuss this or remove the citation.

**Comment by carleyjmartin** [comment]
@bharatreddy 
Sure thing, we can just leave it with the plain description: 'This is slant range divided by two' then it's available for those who want it but it's on the user to decide what scientific merit using it gives them, rather than on us.

**Comment by bharatreddy** [comment]
@carleyjmartin: That sounds better to me. We can discuss this during the next Pydarn meeting.

**Comment by francistee26** [comment]
Hello @carleyjmartin I hope you are doing well. I was just wondering what the status of the half_slant range? I installed the recently released pydarn 3.0 to use with the MUSIC algorithm but it did not work. I discovered that it was not included in the pydarn 3.0 release.

**Comment by carleyjmartin** [comment]
Hey @francistee26 , there has not been a new release since 3.0 (april?) so the half slant updates are waiting in develop branch until then. You should be able to install develop and use it on that branch, let me know if you need help with that.

**Comment by carleyjmartin** [comment]
Discussion can continue on the release PR if required.
