### ISSUE TITLE
ENH: More standardized setup.py

### ISSUE THREAD

**Issue by asreimer** [SuperDARN/pydarn#3]
As per [this](https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=data_files#configuring-setup-using-setup-cfg-files) we should strive to use `setup.cfg`.

Also, we should use a MANIFEST.in file for including other files into the pydarn package as per [this](https://github.com/pypa/sampleproject/issues/30#issuecomment-143947944).

In summary, we should:
1) Use a `setup.cfg` file
2) Use a `MANIFEST.in` file and `include_package_data=True`

**Comment by mts299** [comment]
Thanks for the suggestions but please make sure to give reasoning so people can understand why you would want to use setup.py or MANIFEST.in 

Also, I am not convinced about include_package_data=True. 
Users probably don't want to download data. 
Also, this might have to be further discussed with the test data repo we have right now.

**Comment by asreimer** [comment]
Just to bring some clarity here, this issue was created to track what is fundamentally an architectural change to how the setup of this package is put together. It didn't seem in the scope of #2 so I am tracking it here as a to do later at the very least.

As for more details, using a MANIFEST.in and setup.cfg seems to the be best practices of many projects and seems to help with cross platform compatibility. I can dig deeper if needed.

**Comment by mts299** [comment]
I implemented in PR #2  as it showed to be an issue with installing configuration files needed for pydarn. 

Closing ticket. Further discussion can be done in #2
