### ISSUE TITLE
Update needed on PyHC page

### ISSUE THREAD

**Issue by aburrell** [SuperDARN/pydarn#316]
# Documentation 

The pydarn entry on the PyHC page needs a self-evaluation to be performed so that the community in general knows that this is an active project.

## Purpose

- [x] update
- [ ] new 
- [ ] remove
- [ ] typo/grammar change
- [ ] markdown improvement

## Category 

- [x] OTHER
- [ ] code documentation
- [ ] wiki
- [ ] README
- [ ] installation guide
    - [ ] OS specifics
    - [ ] dependency
    - [ ] environment
- [ ] tutorials
    - [ ] plotting
    - [ ] io
    - [ ] utils/exceptions
- [ ] examples
- [ ] citing/licensing
- [ ] trouble shooting
    - [ ] installation
    - [ ] tutorials
- [ ] history
- [ ] guidelines
    - [ ] developer
    - [ ] communication

## Details

https://heliopython.org/projects/

**Comment by carleyjmartin** [comment]
Thanks Angeline, I had no idea this even existed!

**Comment by Shirling-VT** [comment]
Me neither, @aburrell can you provide some instructions how to do the self evaluation in PyHC or where we can find such information?

**Comment by carleyjmartin** [comment]
@Shirling-VT I've got it covered, you have to read a bit of their github repo to figure it out. Who should I put down as contact though, should I put the group as a whole?

**Comment by aburrell** [comment]
The group is probably the best idea.  That way if the head changes the point of contact is still correct.

**Comment by Shirling-VT** [comment]
@carleyjmartin @aburrell Thanks, sounds like a good idea to me.

**Comment by carleyjmartin** [comment]
Okay, the PR is made and waiting approval 👍 

https://github.com/heliophysicsPy/heliophysicsPy.github.io/pull/277

**Comment by carleyjmartin** [comment]
PR was approved and we're all updated on the website now.
