### ISSUE TITLE
New Feature: Ray Tracing Calculation and Plotting

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#325]
# New Feature

**Name**: ray tracing

**module**:  *ray_tracing.py* 

**package**: *plotting/utils*

## Scope

This will be a large project for us, I had started working on this for our groups use last year, but did not finish as it's surprisingly large and will likely be a series of pull requests. 
This can include the code to calculate ray tracing in utils and then create plots associated with ray tracing. 
I will expand on this comment soon with some more information about what people want, I'm just adding it here now as it was requested by a PI and other users previously. You can check out the general idea of this on the VT website: http://vt.superdarn.org/tiki-index.php?page=Ray-tracing

### pyDARN Checklist 

-  [ ] Does this fit within pyDARN's scope?  (Is this too big for us?)
-  [ ] Is this a minor change i.e., new small utility function?
-  [x] Is this a major change i.e., new plotting function?
-  [x] Do you need help developing it?

**Comment by bharatreddy** [comment]
@carleyjmartin: I spent time on this (Sebastien's ray-tracing implementation, the one you refer to on our website). We can discuss this in the next meeting.

**Comment by hiyadutuje** [comment]
This is a good idea!

**Comment by carleyjmartin** [comment]
This is currently being developed as a pydarn plug-in as it will require some additional install instructions beyond basic pydarn, for more info you will be able to find this on the plugs ins repo https://github.com/SuperDARN/pydarn_plugins when it is developed further. For now I will close this issue, any questions comments and testing about this feature can be opened on the plug-in repo, thanks!
