### ISSUE TITLE
Discussion: hdw Installation Quirks

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#349]
# Discussion 

**Topic:** Issues with `hdw` installation/ quirks I've noticed and want to see if anyone else is having this issue.

## Description

So, since this morning, when using `git clone` to clone the repo, the `hdw` files are not being downloaded at the time of cloning. However, when I `import pydarn`, the `hdw` files were downloaded in a zip file and inflated, then installed (so nothing breaks when actually using pyDARN). I've never had this happen to me before and Alicreance also noticed that the `hdw` files were not downloaded on clone, but then when he tried to import it did not install them, so it's not acting quite right.

If anyone has a similar experience please let me know and give your traceback in the comments as I'm not sure if this is just something new in our dependencies or it's a problem we need to solve yet.

## Category

- [ ] User-friendly  
- [x] Software Design
- [ ] Data related
- [ ] Capabilities
- [ ] Clarity 
- [ ] Workflow

**Comment by RemingtonRohel** [comment]
Have you tried using `git submodule init` then `git submodule update` after cloning? I think that since the `hdw` repo is a submodule you have to take these steps.

**Comment by carleyjmartin** [comment]
Worked like a charm, I'll add this to the instructions I give!

**Comment by carleyjmartin** [comment]
For anyone searching this problem when cloning the repo before I close this issue, this is the process for testing a new branch when cloning:

Make sure you have uninstalled any previous pydarn installations
`pip3 uninstall pydarn`​
Clone the git repository
`git clone https://github.com/SuperDARN/pydarn.git`
Move into the new git repository
`cd pydarn​`
Checkout the branch you want to test
`git checkout branchname`
Initialize and update submodule to get hdw
`git submodule init`
`git submodule update`
Install pydarn
`pip3 install .`

Alternatively, if you don't want to clone you can install right from the branch using:
`pip3 install git+https://github.com/superdarn/pydarn@branchname`

As always, I recommend installing anything new in a virtual environment, but that is up to you!

Alternatively, alternatively, if you are having other issues with the hdw files not installing, you can git clone the hdw repository in the utils directory either in your installation or your cloned pydarn repo. https://github.com/SuperDARN/hdw Feel free to email me if you need help!
