### ISSUE TITLE
Kwargs for specific features of plots

### ISSUE THREAD

**Issue by RemingtonRohel** [SuperDARN/pydarn#361]
# New Feature

**Name**: Kwargs handling

**module**:  everywhere

**package**: every package

## Scope

Passing kwargs to any and all matplotlib plotting calls.

## Description

It would be a great addition if kwargs handling was extended so the user could specify kwargs for a specific feature of a plot. For example, plotting a geographic plot with coastlines, and I want to change the line thickness or color or alpha of the coastlines. Perhaps there can be a standardized `coastlines_kwargs` dictionary as an entry into `kwargs` that contains the kwargs specific for plotting the coastlines. This sort of behaviour could then be extended to all the interconnected plotting that pyDARN does, and would need to be pretty extensively documented in the function docstrings and ReadTheDocs so that it's clear to the users how to make use of this. 

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [ ] Is this a minor change i.e., new small utility function?
-  [x] Is this a major change i.e., new plotting function?
-  [x] Do you need help developing it? 
-  [ ] Have you created a pyDARN GitHub [project](https://github.com/SuperDARN/pydarn/projects) to show the tasks needed to be done? 

### Development help

*pyDARN does not have a dedicated development team on hand to full feature development. 
However, if you are able to provide some time and help, the community will try to aid you the best way they can in making your feature possible.*

*If you need help please indicate what expertise you are looking for:*
- [x] developer help with design and integration of code
- [ ] scientific help with ensuring what you develop is scientifically correct/accurate
- [x] project management to help organize what steps need to be taken to make this possible 

## User Interface 

Example:

```python3
gridplot = pydarn.Grid.plot_grid(grid_data,
                                 start_time=start_time,
                                 lowlat=60,
                                 radar_label='INV',
                                 coastline=True,
                                 cmap=cmap,
                                 coastlines_kwargs={'alpha'=0.5, 'linewidth'=1.0})
```

**Comment by RemingtonRohel** [comment]
I realize after writing this that I can likely achieve the functionality of the above example by initializing an instance of `Projs` then passing that in as a kwarg to plot_grid. However, kwargs for Projs.POLAR is not currently implemented (it's there as a parameter to `axis_polar`, but is unused). 

However, another example where specific kwargs of this sort may be useful: 
Passing in unique colors to ACF plots so that power and phase are different than the defaults and each other. Simply passing `color=...` won't be sufficient, since there are multiple `ax.plot()` and `ax.scatter()` calls, so more granularity is needed.

**Comment by carleyjmartin** [comment]
I think this will tie in nicely with a refactor for ax handlng too.
