### ISSUE TITLE
DISCUSSION: Addition of Siziwang, Longjing and Hejing Radar information

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#365]
# Discussion 

**Topic:**

New radars!

## Description

This will need to be added to the superdarn_radars.py file, and a refresh of the submodule hdw files when they are updated properly. 
I'm happy to do this, this is just a reminder.

**Comment by egthomas** [comment]
@carleyjmartin hardware information for the new NSSC radars is now available in the main branch of the hdw repository (https://github.com/SuperDARN/hdw/pull/7).
