### ISSUE TITLE
pip3 prereq needed?

### ISSUE THREAD

**Issue by ksterne** [SuperDARN/pydarn#37]
Hey all, I'm largely a n00b here, so sorry if this has been covered elsewhere, though I couldn't find it anywhere.  Has anyone looked at pydarn in the new Ubuntu20? I know it's not released yet...but will be soon.

Anywho, I was using a VM with that and think I didn't skimp on the software packages to be installed.  But starting with the install instructions on the readthedocs I didn't have pip3 installed even though I have Python3.8.2.  Anyone else run into that or is that maybe from using a pre-release of the OS?

EDIT: Also didn't come standard with git.  These seem to both be needed to run:
`pip3 install --user git+https://github.com/superdarn/pydarn@develop`

**Comment by mts299** [comment]
Hey, @ksterne is possible you could go to the PR for the first release as some updated have been made there and most of my focus is there when I get time. 

The instructions have been updated as well.

`pip` may still install to python 3.0 especially with newer ubuntu OS systems. I haven't tested it with the newest one. 

Yes, we are updating the documentation as @asreimer mentioned this in the PR just currently a bit behind in getting things all done. 

Thank you for trying it out!

**Comment by asreimer** [comment]
@ksterne you can usually check which python version of pip you are running with:

    $ pip --version

it will tell you which version of python it is running on. If not (you have a super old version of pip maybe?), you can do this:

    $ less `which pip`

there will be a reference to the version of python it is running on.

Alternatively, if you set up your own python virtual environment and always use that, you will know :). A rough guide for ubuntu and python 3.8 (create a venvs directory in your home directory and install a python 3 virtual environment to it, then automatically activate that environment when you open a shell using your .bashrc file):

    $ sudo apt-get update
    $ sudo apt-get install python3-virtualenv python3-pip
    $ cd ~/
    $ mkdir venvs
    $ virtualenv -p python3.8 ~/venvs/py38
    $ echo "source $HOME/venvs/py38/bin/activate" >> ~/.bashrc

Then open a new terminal and you should see a `(py38)` in the prompt.

**Comment by asreimer** [comment]
Also, yes, you need git to pull down and install git repos with pip https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

**Comment by ksterne** [comment]
Yea, I guess my comment was that from: https://pydarn.readthedocs.io/en/latest/user/install/ and Ubuntu 20, pip and git aren't coming with it.  So I was thinking that under the prerequisites section, we might need to add pip and git.  This is likely fixed by the apt-get install for pip that @asreimer noted.

**Comment by mts299** [comment]
Thank you, again if you have any further comments please redirect to the release PR #36  as I am focusing most of my attention there and any documentation changes should be noted there so I can make sure to catch them.

**Comment by mts299** [comment]
Closing this issue.
