### ISSUE TITLE
rawACF read

### ISSUE THREAD

**Issue by alexchartier** [SuperDARN/pydarn#56]
When trying to read a rawACF I get this error:

pydarn.exceptions.superdarn_exceptions.SuperDARNFieldMissingError: Error: The following fields in record 14 are missing: {'acfd'}

Example code (using python3.7)
in_fn = 'pydarn/raw_sas/20090101.1201.00.sas.rawacf'
sdf = pydarn.SDarnRead(in_fn)
rwr = sdf.read_rawacf()

**Comment by mts299** [comment]
Hi @alexchartier I noticed this issue a while back and made a fix for it on PR #45 just waiting for someone to test it for me to merge and then make a patch release.

**Comment by kevinkrieger** [comment]
I believe there's something wrong with that file. Here is the result of my testing with PR #45 :

> >>> import pydarn
> >>> in_fn = '/home/kevin/PycharmProjects/pydarn/20090101.1201.00.sas.rawacf.bz2'
> >>> sd = pydarn.SDarnRead(in_fn)
> >>> r = sd.read_rawacf()
> Error: /home/kevin/PycharmProjects/pydarn/20090101.1201.00.sas.rawacf.bz2 contains an block size 643383601 > remaining bytes 13381653 at record = 0.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/superdarn.py", line 421, in read_rawacf
>     self._read_darn_records(file_struct_list)
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/superdarn.py", line 372, in _read_darn_records
>     self._read_darn_record(format_fields)
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/superdarn.py", line 347, in _read_darn_record
>     record = self.read_record()
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/dmap.py", line 449, in read_record
>     remaining_bytes, "remaining bytes")
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/dmap.py", line 287, in bytes_check
>     self.rec_num)
> pydarn.exceptions.dmap_exceptions.MismatchByteError: Error: /home/kevin/PycharmProjects/pydarn/20090101.1201.00.sas.rawacf.bz2 contains an block size 643383601 > remaining bytes 13381653 at record = 0.
> >>> 
>

**Comment by kevinkrieger** [comment]
I've tested with PR #45 and this is the result:

>>> in_fn = '/home/kevin/PycharmProjects/pydarn/20090101.1201.00.sas.rawacf'
>>> sd = pydarn.SDarnRead(in_fn)
>>> r = sd.read_rawacf()
>>>

**Comment by alexchartier** [comment]
Sounds like it's ready to merge back in and make a patch release then? Let me know when the release comes out.
