### ISSUE TITLE
reading bz2 files

### ISSUE THREAD

**Issue by kevinkrieger** [SuperDARN/pydarn#58]
I noticed that pydarn will incorrectly classify an input bz2 file as having an issue with the first record.
If it's not the intention of pydarn to handle compressed files, then it should produce an error message saying so. If it's the intention of pydarn to handle compressed files, it should uncompress it first.

> 
> >>> import pydarn
> >>> in_fn = '/home/kevin/PycharmProjects/pydarn/20090101.1201.00.sas.rawacf.bz2'
> >>> sd = pydarn.SDarnRead(in_fn)
> >>> r = sd.read_rawacf()
> Error: /home/kevin/PycharmProjects/pydarn/20090101.1201.00.sas.rawacf.bz2 contains an block size 643383601 > remaining bytes 13381653 at record = 0.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/superdarn.py", line 421, in read_rawacf
>     self._read_darn_records(file_struct_list)
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/superdarn.py", line 372, in _read_darn_records
>     self._read_darn_record(format_fields)
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/superdarn.py", line 347, in _read_darn_record
>     record = self.read_record()
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/dmap.py", line 449, in read_record
>     remaining_bytes, "remaining bytes")
>   File "/home/kevin/PycharmProjects/pydarn/pydarn/io/dmap.py", line 287, in bytes_check
>     self.rec_num)
> pydarn.exceptions.dmap_exceptions.MismatchByteError: Error: /home/kevin/PycharmProjects/pydarn/20090101.1201.00.sas.rawacf.bz2 contains an block size 643383601 > remaining bytes 13381653 at record = 0.
>

**Comment by mts299** [comment]
The only issue is knowing how to detect a compression file checking extensions is not bullet proof.

**Comment by mts299** [comment]
pyDARN does not deal with compression files as you can compress files in many different ways and there are tons of useful libraries to do so. There is also an example of how to read in a compressed file in the pyDARN documentation and tutorial. 

@kevinkrieger please specify how you can detect a compressed file and I can look into developing it in. Thank you for pointing this out. I can it documentation that pyDARN does not support compressed files.

**Comment by kevinkrieger** [comment]
I think that you can get around this by using this code from PR #41. It works well.

`
def open_compressed_file(input_filename):
    """
    Check the input filename for compression style and return an uncompressed filestream
    This method uses magic numbers inherent to various file types, and imports what it needs,
    when it needs it. The result is a filestream ready for pydarn.SDarnRead(returnval, True).
    Note that SDarnRead takes a boolean value True if the first argument is a filestream.
    Future Work
    -----------
    Support other possible compression types
    Parameters
    ----------
    input_filename: str
        A possibly compressed file to open
    Returns
    -------
    A filestream object from the opened input_filename
    See Also
    --------
    https://www.garykessler.net/library/file_sigs.html
    """
    # Normally, IQ files are gzip compressed, try that first.
    # Note that there are other ways to do this, but they rely on python versions >= 3.7
    # For various file types, magic numbers are below:
    # gzip:     0x1F8B08
    # bzip:     0x425A68
    # tar.z:    0x1F9D OR 0x1FA0
    # lha,lzh:  0x2D6C68
    # 7z:       0x377ABCAF271C
    # zip:      0x504B4C495445  *** At 30 byte offset ***
    # zip:      0x504B537058    *** At 526 byte offset ***
    # rar:      0x526172211A0700 OR 0x526172211A070100
    with open(input_filename, 'rb') as file_to_test:
        magic_number = binascii.hexlify(file_to_test.read(3))

    if magic_number == b'1f8b08':  # Note that you need lowercase hex chars
        import gzip
        return gzip.open(input_filename).read()
    elif magic_number == b'425a68':
        import bz2
        return bz2.open(input_filename).read()
    else:
        return open(input_filename, 'rb').read()  # You need to open this in binary mode
    # TODO: Possible other compression types
    # TODO: catch any exceptions this may raise`

**Comment by mts299** [comment]
Are hex codes always going to be different for each type of compression?

**Comment by mts299** [comment]
K I will do bzip2, gzip, and zip for now

**Comment by mts299** [comment]
Gonna move this issue to pyDARNio

**Comment by mts299** [comment]
Moved this issue to pyDARNio: https://github.com/SuperDARN/pyDARNio/issues/1
