### ISSUE TITLE
Sub repo PyDARNio 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#70]
With the announcement of pyDARN splitting off the io, I am getting feedback on how users want the io to stay in to make pyDARN one complete package. 
As I don't disagree with either separate or keep together, I thought an idea to achieve the best of both worlds. 

We can make pyDARNio a dependency of pyDARN via install in setup file or sub-repo. 
I am leaning to the sub-repo idea. 

This way, we can keep changes separate but have io together with pyDARN for those that prefer it that way. 

I will leave this up as an agenda topic for the next meeting.

**Comment by carleyjmartin** [comment]
To kick off some discussion here. My use case will need both, and would be easier for me if I can install everything in one go and import from pydarn.

**Comment by mts299** [comment]
Thanks for the insight! I am hoping to get more feedback to better understand the use cases so we can make a decision on this without a meeting.
