### ISSUE TITLE
Can you read .fit file using pydarn?

### ISSUE THREAD

**Issue by TsigeA** [SuperDARN/pydarn#74]
Hi, I recently installed pydarn to work on SuperDARN data. I am able to read and do some plots shown on the tutorial for .fitacf files. My problem is I have other data with the old format, '.fit', which I need to read and create a data frame for further analysis (time series analysis). So I am wondering if it is possible to read .fit files using pydarn. 

Thank you!

**Comment by mts299** [comment]
Hi @TsigeA 

Doesn't look like it, I cannot get it to work with `DmapRead` class which only reads DMap files. Looks like `fit` files have a different structure to them. 

One way to get around this is by using [RST](https://github.com/superdarn/rst)  [`fittofitacf`](https://superdarn.github.io/rst/superdarn/src.bin/tk/reformat/fittofitacf/index.html) to convert the fit files to fitacf then read in via pydarn and plot :) 

Sorry for the inconvenience, I will look at this for future features of pyDARNio

Let me know if this solves your problem and if you need any help getting this working. 
RST also doesn't work well with Windows so if you need me to I can convert the files for you.

**Comment by TsigeA** [comment]
@mts299 Thank you very much!
I have managed to install RST and convert the .fit data to .fitACF. Now it is working fine.
I really appreciate your help!

Regards  
 Tsige
